### ISSUE TITLE
TemplateAssertionError: no filter named 'tojson'

### ISSUE THREAD

**Issue by eaubin** [simonw/datasette#101]
I get an exception clicking on the table link: 

```
2017-11-15 08:40:10 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/datasette/app.py", line 155, in get
    return await self.view_get(request, name, hash, **kwargs)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/datasette/app.py", line 219, in view_get
    **context,
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/sanic_jinja2/__init__.py", line 84, in render
    return html(self.render_string(template, request, **context))
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/sanic_jinja2/__init__.py", line 81, in render_string
    return self.env.get_template(template).render(**context)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/datasette/templates/table.html", line 29, in template
    <pre>params = {{ query.params|tojson(4) }}</pre>
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/environment.py", line 515, in _generate
    return generate(source, self, name, filename, defer_init=defer_init)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/compiler.py", line 62, in generate
    generator.visit(node)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/compiler.py", line 849, in visit_Template
    self.blockvisit(block.body, block_frame)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/compiler.py", line 492, in blockvisit
    self.visit(node, frame)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/compiler.py", line 1172, in visit_If
    self.blockvisit(node.body, if_frame)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/compiler.py", line 492, in blockvisit
    self.visit(node, frame)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/compiler.py", line 1353, in visit_Output
    self.visit(argument, frame)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/compiler.py", line 1565, in visit_Filter
    self.fail('no filter named %r' % node.name, node.lineno)
  File "/Users/e/anaconda3-4.2.0/lib/python3.5/site-packages/jinja2/compiler.py", line 427, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: no filter named 'tojson'
```

**Comment by eaubin** [comment]
This is a duplicate of https://github.com/simonw/datasette/issues/100
