### ISSUE TITLE
"_searchmode=raw" throws an index out of range error when combined with "_search_COLUMN"

### ISSUE THREAD

**Issue by clausjuhl** [simonw/datasette#1134]
Hi Simon!
Maybe it's just me, but when [using _searchmode=raw (trying to enable wildcard-searching) in combination with the "_search_COLUMN"-table argument](https://byraadsarkivet.aarhus.dk/db/cases?_searchmode=raw&_search_title=sundhedsfrem*), I get a list index out of range error. [When combining with the simpler "_search"-argument everything works, including wildcard-seaches.](https://byraadsarkivet.aarhus.dk/db/cases?_search=sundhedsfrem*&_searchmode=raw). Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/cjk/.local/share/virtualenvs/minutes-jMDZ8Ssk/lib/python3.7/site-packages/datasette/utils/asgi.py", line 122, in route_path
    return await view(new_scope, receive, send)
  File "/Users/cjk/.local/share/virtualenvs/minutes-jMDZ8Ssk/lib/python3.7/site-packages/datasette/utils/asgi.py", line 196, in view
    request, **scope["url_route"]["kwargs"]
  File "/Users/cjk/.local/share/virtualenvs/minutes-jMDZ8Ssk/lib/python3.7/site-packages/datasette/views/base.py", line 204, in get
    request, database, hash, correct_hash_provided, **kwargs
  File "/Users/cjk/.local/share/virtualenvs/minutes-jMDZ8Ssk/lib/python3.7/site-packages/datasette/views/base.py", line 342, in view_get
    request, database, hash, **kwargs
  File "/Users/cjk/.local/share/virtualenvs/minutes-jMDZ8Ssk/lib/python3.7/site-packages/datasette/views/table.py", line 393, in data
    search_col = key.split("_search_", 1)[1]
IndexError: list index out of range

```

**Comment by simonw** [comment]
Thanks for the bug report!

**Comment by simonw** [comment]
A fix for this should be available if you upgrade to 0.52.5

**Comment by simonw** [comment]
https://byraadsarkivet.aarhus.dk/db/cases?_searchmode=raw&_search=sundhedsfrem* is an absolutely beautiful example of a themed Datasette! Very excited to show this to people.

**Comment by clausjuhl** [comment]
Hi Simon

Thank you for the quick fix! And glad you like our use of Datasette (launches 1. january 2021). It's a site that currently (more to come) makes all minutes and their annexes from Aarhus City Council and the major committees (1997-2019) available to the public. So we're putting Datasette to good use :)
