### ISSUE TITLE
Better internal database_name for _internal database

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1155]
https://latest.datasette.io/login-as-root then https://latest.datasette.io/_internal

<img width="1627" alt="_schemas__columns__132_rows" src="https://user-images.githubusercontent.com/9599/102668086-e70bfe00-413f-11eb-927d-e37ec9238e12.png">

That `database_name` is ugly. It should just be `_internal`.

**Comment by simonw** [comment]
There's some messy code that needs fixing here. The `datasette.databases` dictionary right now has a key that corresponds to the `/_schemas` URL in the path, and a value that`s a `Database()` object. BUT... the `Database()` object doesn't know what its key is.

While fixing this I should fix the issue where Datasette gets confused by multiple databases with the same stem: https://github.com/simonw/datasette/issues/509

**Comment by simonw** [comment]
The code for building up that `.databases` dictionary is a bit convoluted. Here's the code that adds a `:memory:` database if the user specified `--memory` OR if there are no files to be attached:

https://github.com/simonw/datasette/blob/ebc7aa287c99fe6114b79aeab8efb8d4489a6182/datasette/app.py#L221-L241

I'm not sure why I wrote it this way, instead of just calling `.add_database(":memory:", Database(..., is_memory=True)`.

**Comment by simonw** [comment]
Here's the commit where I added it. https://github.com/simonw/datasette/commit/9743e1d91b5f0a2b3c1c0bd6ffce8739341f43c4 - I didn't yet have the `.add_database()` mechanism. Today the `MEMORY` object bit is no longer needed.

**Comment by simonw** [comment]
A `Database` should have a `.name` which is unique across the Datasette instant. The `path` should be optional, only set for file databases. A new `.memory_name` property can be used for shared memory databases.

**Comment by simonw** [comment]
`Database` internal class is documented here: https://docs.datasette.io/en/latest/internals.html#database-class

**Comment by simonw** [comment]
`datasette-graphql` returns an error due to this issue:

<img width="878" alt="GraphiQL_and_fixtures__compound_three_primary_keys__1_001_rows" src="https://user-images.githubusercontent.com/9599/102677257-61e01380-4156-11eb-8f88-fe26b9c4a40b.png">

On the console:
```
INFO:     127.0.0.1:63116 - "POST /graphql/_internal HTTP/1.1" 500 Internal Server Error
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
  File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/datasette_graphql/utils.py", line 603, in resolve_table
    data, _, _ = await view.data(
  File "/Users/simon/Dropbox/Development/datasette/datasette/views/table.py", line 304, in data
    db = self.ds.databases[database]
graphql.error.located_error.GraphQLLocatedError: ':memory:c6dd5abe1a757a7de00d99b699175bd33d9a575f05b5751bf856b8656fb07edd'
```

**Comment by simonw** [comment]
I removed that `MEMORY` object() in dcdfb2c301341d45b66683e3e3be72f9c7585b2f

**Comment by simonw** [comment]
Fun query:
```sql
select table_name, group_concat(name, ', ') from columns group by database_name, table_name
```
https://latest.datasette.io/_internal?sql=select+table_name%2C+group_concat%28name%2C+%27%2C+%27%29+from+columns+group+by+database_name%2C+table_name

**Comment by simonw** [comment]
I'm going to have the `.add_database()` method select the name used in the path, de-duping against any existing names. It will then set database.name to that so that the database has access to its own name.
