### ISSUE TITLE
--port option should validate port is between 0 and 65535

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1226]
Currently throws an ugly error message:
```
(datasette-graphql) datasette-graphql % datasette fivethirtyeight.db -p 80094
INFO:     Started server process [45497]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/datasette-graphql-n1OSJCS8/bin/datasette", line 8, in <module>
    sys.exit(cli())
...
    server = await loop.create_server(
  File "/Users/simon/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 1461, in create_server
    sock.bind(sa)
OverflowError: bind(): port must be 0-65535.
```

**Comment by simonw** [comment]
This check needs to happen in two places:

https://github.com/simonw/datasette/blob/9603d893b9b72653895318c9104d754229fdb146/datasette/cli.py#L222-L227

https://github.com/simonw/datasette/blob/9603d893b9b72653895318c9104d754229fdb146/datasette/cli.py#L328-L333

**Comment by simonw** [comment]
I'm OK with the current error message shown if you try to use too low a port:
```
datasette fivethirtyeight.db -p 800 
INFO:     Started server process [45511]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 13] error while attempting to bind on address ('127.0.0.1', 800): permission denied
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
```

**Comment by simonw** [comment]
I can use `click.IntRange(min=None, max=None)` for this. https://click.palletsprojects.com/en/7.x/options/#ranges - inclusive on both edges.

**Comment by simonw** [comment]
This broke CI: https://github.com/simonw/datasette/runs/1929355965?check_suite_focus=true
