### ISSUE TITLE
Official Datasette Docker image should use SQLite >= 3.31.0 (for generated columns)

### ISSUE THREAD

**Issue by jcgregorio** [simonw/datasette#1376]
Trying to run datasette via the Docker container doesn't seem to work:

```
$ docker run -p 8001:8001 -v `pwd`:/mnt     datasetteproject/datasette     datasette -p 8001 -h 0.0.0.0 /mnt/fixtures.db
Traceback (most recent call last):
  File "/usr/local/bin/datasette", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/datasette/cli.py", line 544, in serve
    asyncio.get_event_loop().run_until_complete(check_databases(ds))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/datasette/cli.py", line 584, in check_databases
    await database.execute_fn(check_connection)
  File "/usr/local/lib/python3.9/site-packages/datasette/database.py", line 155, in execute_fn
    return await asyncio.get_event_loop().run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/datasette/database.py", line 153, in in_thread
    return fn(conn)
  File "/usr/local/lib/python3.9/site-packages/datasette/utils/__init__.py", line 892, in check_connection
    for r in conn.execute(
sqlite3.DatabaseError: malformed database schema (generated_columns) - near "AS": syntax error
```

I have confirmed that the downloaded `fixtures.db` database is fine:

```
[skia-public] jcgregorio@jcgregorio840 ~/Downloads 
$ sqlite3 fixtures.db 
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> pragma integrity_check;
ok
sqlite> 

```

**Comment by simonw** [comment]
Oh good catch - this is a SQLite version issue.

The `fixtures.db` file used on https://latest.datasette.io/ includes a generated column (for testing purposes) which is a feature added in SQLite 3.31.0 on 2020-01-22.

https://latest.datasette.io/-/versions

But... it looks like the packaged Datasette Docker container doesn't have that SQLite version!

I should fix that. I'm renaming this issue.

**Comment by simonw** [comment]
Alternative fix would be to update that section of the documentation - if the container upgrade proves tricky I can fall back on that.

**Comment by simonw** [comment]
Actually it looks like there is a PR open already that addresses this: #1296

**Comment by simonw** [comment]
https://github.com/simonw/datasette/commit/2c31d1cd9cd3b63458ccbe391866499fa3f44978
