### ISSUE TITLE
OSError: AF_UNIX path too long in ds_unix_domain_socket_server

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1407]
Got this exception while working on #1406.

```
    @pytest.fixture(scope="session")
    def ds_unix_domain_socket_server(tmp_path_factory):
        socket_folder = tmp_path_factory.mktemp("uds")
        uds = str(socket_folder / "datasette.sock")
        ds_proc = subprocess.Popen(
            ["datasette", "--memory", "--uds", uds],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=tempfile.gettempdir(),
        )
        # Give the server time to start
        time.sleep(1.5)
        # Check it started successfully
>       assert not ds_proc.poll(), ds_proc.stdout.read().decode("utf-8")
E       AssertionError: INFO:     Started server process [48453]
E         INFO:     Waiting for application startup.
E         INFO:     Application startup complete.
E         Traceback (most recent call last):
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/bin/datasette", line 33, in <module>
E             sys.exit(load_entry_point('datasette', 'console_scripts', 'datasette')())
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
E             return self.main(*args, **kwargs)
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/click/core.py", line 1062, in main
E             rv = self.invoke(ctx)
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
E             return _process_result(sub_ctx.command.invoke(sub_ctx))
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
E             return ctx.invoke(self.callback, **ctx.params)
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/click/core.py", line 763, in invoke
E             return __callback(*args, **kwargs)
E           File "/Users/simon/Dropbox/Development/datasette/datasette/cli.py", line 583, in serve
E             uvicorn.run(ds.app(), **uvicorn_kwargs)
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/uvicorn/main.py", line 393, in run
E             server.run()
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/uvicorn/server.py", line 50, in run
E             loop.run_until_complete(self.serve(sockets=sockets))
E           File "/Users/simon/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
E             return future.result()
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
E             await self.startup(sockets=sockets)
E           File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.8/site-packages/uvicorn/server.py", line 133, in startup
E             server = await asyncio.start_unix_server(
E           File "/Users/simon/.pyenv/versions/3.8.2/lib/python3.8/asyncio/streams.py", line 132, in start_unix_server
E             return await loop.create_unix_server(factory, path, **kwds)
E           File "/Users/simon/.pyenv/versions/3.8.2/lib/python3.8/asyncio/unix_events.py", line 296, in create_unix_server
E             sock.bind(path)
E         OSError: AF_UNIX path too long
E         
E       assert not 1
E        +  where 1 = <bound method Popen.poll of <subprocess.Popen object at 0x106924af0>>()
E        +    where <bound method Popen.poll of <subprocess.Popen object at 0x106924af0>> = <subprocess.Popen object at 0x106924af0>.poll
```

**Comment by simonw** [comment]
The `path` variable there looked like this:

`/private/var/folders/wr/hn3206rs1yzgq3r49bz8nvnh0000gn/T/pytest-of-simon/pytest-696/popen-gw0/uds0/datasette.sock`

I think what's happening here is that `pytest-xdist` causes `tmp_path_factory.mktemp("uds")` to create significantly longer paths, which in this case is breaking some limit.

So for this code to work with `pytest-xdist` I need to make sure the random path to `datasette.sock` is shorter.

**Comment by simonw** [comment]
I'll try `tempfile.gettempdir()` - on macOS it returns something like `'/var/folders/wr/hn3206rs1yzgq3r49bz8nvnh0000gn/T'` which is still long but hopefully not too long.
