### ISSUE TITLE
Writable canned queries fail to load custom templates

### ISSUE THREAD

**Issue by wragge** [simonw/datasette#1547]
I've created a canned query with `"write": true` set. I've also created a custom template for it, but the template doesn't seem to be found. If I look in the HTML I see (`stock_exchange` is the db name):

`<!-- Templates considered: query-stock_exchange.html, *query.html -->`

My non-writeable canned queries pick up custom templates as expected, and if I look at their HTML I see the canned query name added to the templates considered (the canned query here is `date_search`):

`<!-- Templates considered: query-stock_exchange-date_search.html, query-stock_exchange.html, *query.html -->`

So it seems like the writeable canned query is behaving differently for some reason. Is it an authentication thing? I'm using the built in `--root` authentication.

Thanks!

**Comment by simonw** [comment]
Yes, this is a bug. It looks like the problem is with the `if write:` branch in this code here: https://github.com/simonw/datasette/blob/5fac26aa221a111d7633f2dd92014641f7c0ade9/datasette/views/database.py#L252-L327

Is missing this bit of code:

https://github.com/simonw/datasette/blob/5fac26aa221a111d7633f2dd92014641f7c0ade9/datasette/views/database.py#L343-L347

**Comment by simonw** [comment]
I released this [in an alpha](https://github.com/simonw/datasette/releases/tag/0.60a1), so you can try out this fix using:

    pip install datasette==0.60a1

**Comment by wragge** [comment]
I've installed the alpha version but get an error when starting up Datasette:

```
Traceback (most recent call last):
  File "/Users/tim/.pyenv/versions/stock-exchange/bin/datasette", line 5, in <module>
    from datasette.cli import cli
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/cli.py", line 15, in <module>
    from .app import Datasette, DEFAULT_SETTINGS, SETTINGS, SQLITE_LIMIT_ATTACHED, pm
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/app.py", line 31, in <module>
    from .views.database import DatabaseDownload, DatabaseView
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/views/database.py", line 25, in <module>
    from datasette.plugins import pm
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/plugins.py", line 29, in <module>
    mod = importlib.import_module(plugin)
  File "/Users/tim/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/filters.py", line 9, in <module>
    @hookimpl(specname="filters_from_request")
TypeError: __call__() got an unexpected keyword argument 'specname'
```

**Comment by simonw** [comment]
@wragge thanks, that's a bug! Working on that in #1575.

**Comment by simonw** [comment]
OK, this should hopefully fix that for you:

    pip install https://github.com/simonw/datasette/archive/f36e010b3b69ada104b79d83c7685caf9359049e.zip

**Comment by wragge** [comment]
Yep, that works -- thanks!
