### ISSUE TITLE
__call__() got an unexpected keyword argument 'specname'

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1575]
> I've installed the alpha version but get an error when starting up Datasette:

```
Traceback (most recent call last):
  File "/Users/tim/.pyenv/versions/stock-exchange/bin/datasette", line 5, in <module>
    from datasette.cli import cli
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/cli.py", line 15, in <module>
    from .app import Datasette, DEFAULT_SETTINGS, SETTINGS, SQLITE_LIMIT_ATTACHED, pm
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/app.py", line 31, in <module>
    from .views.database import DatabaseDownload, DatabaseView
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/views/database.py", line 25, in <module>
    from datasette.plugins import pm
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/plugins.py", line 29, in <module>
    mod = importlib.import_module(plugin)
  File "/Users/tim/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/tim/.pyenv/versions/3.8.5/envs/stock-exchange/lib/python3.8/site-packages/datasette/filters.py", line 9, in <module>
    @hookimpl(specname="filters_from_request")
TypeError: __call__() got an unexpected keyword argument 'specname'
```

_Originally posted by @wragge in https://github.com/simonw/datasette/issues/1547#issuecomment-997511968_

**Comment by simonw** [comment]
Looks like `specname` is new in Pluggy 1.0: https://github.com/pytest-dev/pluggy/blob/main/CHANGELOG.rst#pluggy-100-2021-08-25

**Comment by simonw** [comment]
@
