### ISSUE TITLE
Datasette cannot be installed with Rye

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2065]
https://github.com/mitsuhiko/rye

I tried this:

    rye install datasette

But now:

```
% ~/.rye/shims/datasette
Traceback (most recent call last):
  File "/Users/simon/.rye/shims/datasette", line 5, in <module>
    from datasette.cli import cli
  File "/Users/simon/.rye/tools/datasette/lib/python3.11/site-packages/datasette/cli.py", line 17, in <module>
    from .app import (
  File "/Users/simon/.rye/tools/datasette/lib/python3.11/site-packages/datasette/app.py", line 14, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
I think that's because `setuptools` is not included in Rye.

**Comment by simonw** [comment]
Tried this:

    rye install https://github.com/simonw/datasette/archive/refs/heads/main.zip

But got this error:

    Error: Expected one of `@`, `(`, `<`, `=`, `>`, `~`, `!`, `;`, found `:`

I instead downloaded that file and ran:

    rye install main.zip

This worked! And now:
```
~/.rye/tools/main-zip/bin/datasette --version
```
```
datasette, version 1.0a2
```

**Comment by simonw** [comment]
Turned this into a TIL: https://til.simonwillison.net/python/rye

**Comment by simonw** [comment]
I need `pip` as a dependency too:

```
% ~/.rye/tools/main-zip/bin/datasette install datasette-graphql
Traceback (most recent call last):
  File "/Users/simon/.rye/tools/main-zip/bin/datasette", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/simon/.rye/tools/main-zip/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.rye/tools/main-zip/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/simon/.rye/tools/main-zip/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.rye/tools/main-zip/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.rye/tools/main-zip/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.rye/tools/main-zip/lib/python3.11/site-packages/datasette/cli.py", line 365, in install
    run_module("pip", run_name="__main__")
  File "<frozen runpy>", line 222, in run_module
  File "<frozen runpy>", line 142, in _get_module_details
ImportError: No module named pip
```

**Comment by simonw** [comment]
That fixed it - after installing `main.zip` again I ran this and it worked:

    ~/.rye/tools/main-zip/bin/datasette install datasette-graphql

```
% ~/.rye/tools/main-zip/bin/datasette plugins                  
[
    {
        "name": "datasette-graphql",
        "static": true,
        "templates": true,
        "version": "2.2",
        "hooks": [
            "database_actions",
            "extra_template_vars",
            "menu_links",
            "register_routes",
            "startup",
            "table_actions"
        ]
    }
]
```
