### ISSUE TITLE
Cog is failing with round_trip_load_all() YAML error

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2219]
https://github.com/simonw/datasette/actions/runs/7265948406/job/19796712354

```
Run cog --check docs/*.rst
```
```
Traceback (most recent call last):
Checking docs/authentication.rst
  File "docs/authentication.rst", line 220, in <module>
    config_example(cog, """
  File "/home/runner/work/datasette/datasette/docs/metadata_doc.py", line 31, in config_example
    data = round_trip_load(input)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1127, in round_trip_load
    error_deprecation('round_trip_load_all', 'load')
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"round_trip_load_all()" has been removed, use

  yaml = YAML()
  yaml.load(...)

instead of file "/home/runner/work/datasette/datasette/docs/metadata_doc.py", line 31

        data = round_trip_load(input)
```

**Comment by simonw** [comment]
Code at fault:
https://github.com/simonw/datasette/blob/067cc75dfa01612f9a47815b33804361e18bf5c3/docs/metadata_doc.py#L11-L16

**Comment by simonw** [comment]
I can duplicate the bug locally by upgrading `ruamel.yaml`:
```
$ pip freeze | grep yaml
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
$ pip install -U ruamel.yaml
Requirement already satisfied: ruamel.yaml in /Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.10/site-packages (0.17.32)
Collecting ruamel.yaml
  Downloading ruamel.yaml-0.18.5-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.4/116.4 kB 2.9 MB/s eta 0:00:00
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.10/site-packages (from ruamel.yaml) (0.2.7)
Installing collected packages: ruamel.yaml
  Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel.yaml 0.17.32
    Uninstalling ruamel.yaml-0.17.32:
      Successfully uninstalled ruamel.yaml-0.17.32
Successfully installed ruamel.yaml-0.18.5
```
There's a note about that here: https://yaml.readthedocs.io/en/latest/#changelog

> -   the **functions** `scan`, `parse`, `compose`, `load`, `emit`, `serialize`, `dump` and their variants (`_all`, `safe_`, `round_trip_`, etc) have been deprecated (the same named **methods** on `YAML()` instances are, of course, still there.

**Comment by simonw** [comment]
Fixed.
