### ISSUE TITLE
'Datasette' object has no attribute 'table_metadata'

### ISSUE THREAD

**Issue by andig** [simonw/datasette#2316]
After importing a new table I'm getting

    'Datasette' object has no attribute 'table_metadata'

when browsing to table. This is the backtrace:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/app.py", line 1668, in route_path
    response = await view(request, send)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/app.py", line 1861, in async_view_fn
    response = await async_call_with_supported_arguments(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/utils/__init__.py", line 1021, in async_call_with_supported_arguments
    return await fn(*call_with)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/views/table.py", line 747, in table_view
    response = await table_view_traced(datasette, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/views/table.py", line 897, in table_view_traced
    await datasette.render_template(
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/app.py", line 1352, in render_template
    return await template.render_async(template_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/jinja2/environment.py", line 1324, in render_async
    return self.environment.handle_exception()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/templates/table.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/templates/base.html", line 62, in top-level template code
    {% block content %}
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/templates/table.html", line 27, in block 'content'
    {% set action_links, action_title = actions(), "View actions" if is_view else "Table actions" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/jinja2/async_utils.py", line 65, in auto_await
    return await t.cast("t.Awaitable[V]", value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/views/table.py", line 1420, in actions
    extra_links = await await_me_maybe(hook)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/utils/__init__.py", line 115, in await_me_maybe
    value = await value
            ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette_graphql/__init__.py", line 235, in inner
    db_schema = await schema_for_database_via_cache(datasette, database=database)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette_graphql/utils.py", line 81, in schema_for_database_via_cache
    schema = await schema_for_database(datasette, database)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette_graphql/utils.py", line 97, in schema_for_database
    table_metadata = await db.execute_fn(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/database.py", line 282, in execute_fn
    return await asyncio.get_event_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette/database.py", line 280, in in_thread
    return fn(conn)
           ^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette_graphql/utils.py", line 98, in <lambda>
    lambda conn: introspect_tables(conn, datasette, db.name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.6_2/libexec/lib/python3.12/site-packages/datasette_graphql/utils.py", line 672, in introspect_tables
    datasette_table_metadata = datasette.table_metadata(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
```

Not sure what makes this specific table different from the others?

**Comment by andig** [comment]
Anything I can contribute to diagnose/fix this? Right now datasette (installed via Homebrew) is useless as it crashes on almost any table.

**Comment by tddschn** [comment]
Got the same error.

**Comment by simonw** [comment]
This looks like a bug in the GraphQL plugin. I'll take a look tomorrow.

**Comment by andig** [comment]
Would be great to get this fixed as it makes datasette unusable in this case.

**Comment by andig** [comment]
@simonw any update? I'm totally blocked on using datasette due to this error.

**Comment by andig** [comment]
Friendly ping :)

**Comment by andig** [comment]
Friendly ping :)

**Comment by andig** [comment]
Tracked this down: it's a **version mismatch**, not anything special about the table.

The `0.64.6_2` in the path is just the Homebrew Cellar directory name — the Datasette actually running in that venv is a **1.0 alpha** (the traceback line numbers match `1.0a13`: `table.py:747 → table_view_traced`, `app.py:1668`, `app.py:1861`). Real 0.64.6 has none of those frames. `datasette install datasette-graphql` runs pip inside the Homebrew venv and the resolver upgraded `datasette` to a 1.0 alpha while the Cellar path stayed `0.64.6_2`.

The 1.0 alphas **removed** `Datasette.table_metadata()` (present through `1.0a7`, gone by `1.0a13`, later replaced by async `get_resource_metadata()`). `datasette-graphql` registers a `table_actions` hook, so rendering *any* table runs `introspect_tables()` → `datasette.table_metadata(...)` → `AttributeError`. That's why it's every table.

This is fixed upstream in `datasette-graphql` — `main` now precomputes table configs async and no longer calls `table_metadata` from the sync introspection path.

Fixes, easiest first:
1. `datasette install -U datasette-graphql` — pick up the patched plugin.
2. Pin Datasette back to a stable release that still has `table_metadata`: `datasette install 'datasette<1.0'`.
3. `datasette uninstall datasette-graphql` if you don't need GraphQL.

Closing as resolved.
