### ISSUE TITLE
PyOdide test failure

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2351]
https://github.com/simonw/datasette/actions/runs/9469427870/job/26088069712

![CleanShot 2024-06-11 at 09 39 03@2x](https://github.com/simonw/datasette/assets/9599/154558a9-0340-49b4-9558-42480ce643c2)

```
    from typing_extensions import deprecated  # noqa
ImportError: cannot import name 'deprecated' from 'typing_extensions' (/lib/python3.10/site-packages/typing_extensions.py)
```

**Comment by simonw** [comment]
Full stacktrace:

```
Error: Page.evaluate: PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 353, in run_async
    await coroutine
  File "<exec>", line 8, in <module>
  File "/lib/python3.10/site-packages/datasette/app.py", line 39, in <module>
    from .views.base import ureg
  File "/lib/python3.10/site-packages/datasette/views/base.py", line 11, in <module>
    import pint
  File "/lib/python3.10/site-packages/pint/__init__.py", line 18, in <module>
    from .delegates.formatter._format_helpers import formatter
  File "/lib/python3.10/site-packages/pint/delegates/__init__.py", line 12, in <module>
    from . import txt_defparser
  File "/lib/python3.10/site-packages/pint/delegates/txt_defparser/__init__.py", line 12, in <module>
    from .defparser import DefParser
  File "/lib/python3.10/site-packages/pint/delegates/txt_defparser/defparser.py", line 9, in <module>
    from ..base_defparser import ParserConfig
  File "/lib/python3.10/site-packages/pint/delegates/base_defparser.py", line 24, in <module>
    from pint.facets.plain.definitions import NotNumeric
  File "/lib/python3.10/site-packages/pint/facets/__init__.py", line 72, in <module>
    from .context import ContextRegistry, GenericContextRegistry
  File "/lib/python3.10/site-packages/pint/facets/context/__init__.py", line 14, in <module>
    from .definitions import ContextDefinition
  File "/lib/python3.10/site-packages/pint/facets/context/definitions.py", line 19, in <module>
    from ..plain import UnitDefinition
  File "/lib/python3.10/site-packages/pint/facets/plain/__init__.py", line 13, in <module>
    from .definitions import (
  File "/lib/python3.10/site-packages/pint/facets/plain/definitions.py", line 19, in <module>
    from ..._typing import Magnitude
  File "/lib/python3.10/site-packages/pint/_typing.py", line 8, in <module>
    from .compat import Never, TypeAlias
  File "/lib/python3.10/site-packages/pint/compat.py", line 46, in <module>
    from typing_extensions import deprecated  # noqa
ImportError: cannot import name 'deprecated' from 'typing_extensions' (/lib/python3.10/site-packages/typing_extensions.py)
```

**Comment by simonw** [comment]
This is the actual test code: https://github.com/simonw/datasette/blob/e1bfab3fca22e4f8d06dcf419e945f13fc20aef1/test-in-pyodide-with-shot-scraper.sh#L21-L41

**Comment by simonw** [comment]
Running this runs tests locally:

    ./test-in-pyodide-with-shot-scraper.sh 

Got a surprising different error:

```
::1 - - [11/Jun/2024 09:43:46] "GET / HTTP/1.1" 200 -
Error: PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__
    self.ast = next(self._gen)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen
    mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST)
  File "<exec>", line 2
    import micropip
IndentationError: unexpected indent
```

**Comment by simonw** [comment]
That error was fixed by doing this:
```
wheel=$(basename $(ls dist/*.whl) | head -n 1)
```

**Comment by simonw** [comment]
... and now I can replicate that CI bug locally.

**Comment by simonw** [comment]
Fix was to force it to install a modern version of `typing-extensions`:

https://github.com/simonw/datasette/blob/9a3c3bfcc7d30d65514421bd315f1b8b5b735b86/test-in-pyodide-with-shot-scraper.sh#L36-L37
