### ISSUE TITLE
Cannot run datasette on 3.13

### ISSUE THREAD

**Issue by clin1234** [simonw/datasette#2368]
```
❯ datasette
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ךינשגכהד\scoop\persist\python-alpha\Scripts\datasette.exe\__main__.py", line 4, in <module>
    from datasette.cli import cli
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\datasette\cli.py", line 17, in <module>
    from .app import (
    ...<5 lines>...
    )
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\datasette\app.py", line 39, in <module>
    from .views.base import ureg
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\datasette\views\base.py", line 11, in <module>
    import pint
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\pint\__init__.py", line 18, in <module>
    from .delegates.formatter._format_helpers import formatter
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\pint\delegates\__init__.py", line 12, in <module>
    from . import txt_defparser
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\pint\delegates\txt_defparser\__init__.py", line 12, in <module>
    from .defparser import DefParser
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\pint\delegates\txt_defparser\defparser.py", line 10, in <module>
    from . import block, common, context, defaults, group, plain, system
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\pint\delegates\txt_defparser\common.py", line 23, in <module>
    @dataclass(frozen=True)
     ~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\dataclasses.py", line 1295, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\dataclasses.py", line 1043, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
                    'non-frozen one')
TypeError: cannot inherit frozen dataclass from a non-frozen one
```

**Comment by asg017** [comment]
Simon's been working through this in #2321 - and has a PR up in pint at https://github.com/hgrecco/pint/pull/2037 

Though the pint dependency _might_ be removed altogether if we're not able to fix it
