### ISSUE TITLE
Unexpected keyword argument 'hidden'

### ISSUE THREAD

**Issue by dvot197007** [simonw/datasette#566]
I couldn't get a test example running. I am running python 3.6.8 and tried both windows and windows subsystem for linux, getting the same error. My test.db was created by converting a five line csv file with csvs-to-sqlite. The csv file is:
col1, col2, col3
1,2,3
4,5,6
7,8,9
10,11,12
Here is the error message:
(myvenv) davido@DESKTOP-L29G79U:~/dot/datasette-eg$ datasette test.db                                                   Traceback (most recent call last):                                                                                        File "/home/davido/dot/datasette-eg/myvenv/bin/datasette", line 7, in <module>                                            from datasette.cli import cli                                                                                         File "/home/davido/dot/datasette-eg/myvenv/lib/python3.6/site-packages/datasette/cli.py", line 2, in <module>             import uvicorn                                                                                                        File "/home/davido/dot/datasette-eg/myvenv/lib/python3.6/site-packages/uvicorn/__init__.py", line 2, in <module>          from uvicorn.main import Server, main, run                                                                            File "/home/davido/dot/datasette-eg/myvenv/lib/python3.6/site-packages/uvicorn/main.py", line 224, in <module>            headers: typing.List[str],                                                                                            File "/home/davido/dot/datasette-eg/myvenv/lib/python3.6/site-packages/click/decorators.py", line 170, in decorator       _param_memo(f, OptionClass(param_decls, **attrs))                                                                     File "/home/davido/dot/datasette-eg/myvenv/lib/python3.6/site-packages/click/core.py", line 1430, in __init__             Parameter.__init__(self, param_decls, type=type, **attrs)                                                           TypeError: __init__() got an unexpected keyword argument 'hidden'  

Thanks.

**Comment by dvot197007** [comment]
This example now works on my other machine when running from the anaconda prompt. So I'm not sure if this is actually a datasette issue or not.
