### ISSUE TITLE
Unit tests should fail under Python 3.8

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#626]
The unit tests currently pass under Python 3.8.

But... when you actually attempt to run Datasette you get an error:
```
~/Dropbox/Development/datasette $ venv-py3.8.0/bin/datasette --memory -p 8855
Serve! files=() (immutables=()) on port 8855
Traceback (most recent call last):
  File "venv-py3.8.0/bin/datasette", line 11, in <module>
    load_entry_point('datasette', 'console_scripts', 'datasette')()
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/simonw/Dropbox/Development/datasette/datasette/cli.py", line 365, in serve
    uvicorn.run(ds.app(), host=host, port=port, log_level="info")
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/uvicorn/main.py", line 279, in run
    server.run()
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/uvicorn/main.py", line 305, in run
    self.config.setup_event_loop()
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/uvicorn/config.py", line 218, in setup_event_loop
    loop_setup()
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/uvicorn/loops/auto.py", line 3, in auto_loop_setup
    import uvloop
  File "/Users/simonw/Dropbox/Development/datasette/venv-py3.8.0/lib/python3.8/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
  File "uvloop/includes/stdlib.pxi", line 114, in init uvloop.loop
AttributeError: module 'sys' has no attribute 'set_coroutine_wrapper'
~/Dropbox/Development/datasette $ 
```
If Datasette doesn't work under Python 3.8 the tests should fail.

**Comment by simonw** [comment]
I'm giving up on this. I spent a bunch of time trying to get it to work and couldn't.

My final attempt was inspired by https://github.com/encode/uvicorn/blob/e821fd1ff5653f989d500d41fa6ba070858f6843/tests/test_main.py#L10-L32

Here's the code that didn't work:
```
def test_asgi_app(app_client):
    from uvicorn.config import Config
    from uvicorn.main import Server

    class CustomServer(Server):
        def install_signal_handlers(self):
            pass

    def run_server():
        asyncio.set_event_loop(asyncio.new_event_loop())
        print("ooh new loop")
        config = Config(app=app_client.asgi_app, limit_max_requests=1, port=8642)
        config.load()
        server = CustomServer(config=config)
        server.run()

    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
        future = executor.submit(run_server)
        future.result()
        while not server.started:
            print(server.__dict__)
            time.sleep(0.01)
        assert 200 == urllib.request.urlopen("http://localhost:8642/").status
        # This line will raise if there's an exception:
        future.result()
```
I got `RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'`
