### ISSUE TITLE
Nicer error message for heroku publish name clash

### ISSUE THREAD

**Issue by psychemedia** [simonw/datasette#640]
If you try to publish to Heroku using no set name (i.e. the default `datasette` name) and a project already exists under that name, you get a meaningful error report on the first line followed by Py error messages that drown it out:

```
Creating datasette... !
 ▸    Name datasette is already taken
Traceback (most recent call last):
  File "/usr/local/bin/datasette", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/NNNNN/Library/Python/3.7/lib/python/site-packages/datasette/publish/heroku.py", line 124, in heroku
    create_output = check_output(cmd).decode("utf8")
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['heroku', 'apps:create', 'datasette', '--json']' returned non-zero exit status 1.
```

It would be neater if:

- the Py error message was caught;
- the report suggested setting a project name using `-n` etc.

It may also be useful to provide a command to list the current names that are being used, which I assume is available via a Heroku call?

**Comment by simonw** [comment]
`heroku apps --json` returns a JSON list of apps.

`heroku apps --json | sqlite-utils insert /tmp/heroku.db apps -` creates a SQLite database from them, useful for exploring them.
