### ISSUE TITLE
base_url doesn't entirely work for running Datasette inside Binder

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#712]
> Thanks! I'm trying to launch Datasette from *within* a notebook using the jupyter-server-proxy and the new `base_url` parameter. While the assets load ok, and the breadcrumb navigation works, the facet links don't seem to use the `base_url`. Or have I missed something?

_Originally posted by @wragge in https://github.com/simonw/datasette/issues/394#issuecomment-604166918_

**Comment by simonw** [comment]
Weird... the unit test I just added passes. So suggested facets look like they're OK.

And yet the demo in https://mybinder.org/v2/gh/wragge/datasette-test/master?urlpath=lab doesn't work.

**Comment by simonw** [comment]
Here's the truncatted HTML for https://hub.gke.mybinder.org/user/wragge-datasette-test-czqms2oy/proxy/8001/results/articles
```html
<!DOCTYPE html>
<html>
<head>
    <title>results: articles: 400 rows
    </title>
    <link rel="stylesheet" href="/user/wragge-datasette-test-czqms2oy/proxy/8001/-/static/app.css?4434ab">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
/head>
<body class="table db-results table-articles">

<nav class="hd">
    <p class="crumbs">
        <a href="/user/wragge-datasette-test-czqms2oy/proxy/8001/">home</a> /
        <a href="/user/wragge-datasette-test-czqms2oy/proxy/8001/results">results</a>
    </p>
    
</nav>

<div class="bd">

<h1 style="padding-left: 10px; border-left: 10px solid #ff0000">articles</h1>

<h3>400 rows</h3>


<form class="filters" action="/user/wragge-datasette-test-czqms2oy/proxy/8001/results/articles" method="get">
    ...    
    <input type="submit" value="Apply">
</form>

<p><a class="not-underlined" title="select rowid, article_id, title, newspaper_id, newspaper_title, page, date, category, words, illustrated, corrections, url, page_url from articles order by rowid limit 101" href="/user/wragge-datasette-test-czqms2oy/proxy/8001/results?sql=select+rowid%2C+article_id%2C+title%2C+newspaper_id%2C+newspaper_title%2C+page%2C+date%2C+category%2C+words%2C+illustrated%2C+corrections%2C+url%2C+page_url+from+articles+order+by+rowid+limit+101">&#x270e; <span class="underlined">View and edit SQL</span></a></p>

<p class="export-links">This data as <a href="/results/articles.json">json</a>, <a href="/results/articles.csv?_size=max">CSV</a> (<a href="#export">advanced</a>)</p>
    <p class="suggested-facets">
        Suggested facets: <a href="/results/articles?_facet=newspaper_id#facet-newspaper_id">newspaper_id</a>, <a href="/results/articles?_facet=newspaper_title#facet-newspaper_title">newspaper_title</a>, <a href="/results/articles?_facet=page#facet-page">page</a>, <a href="/results/articles?_facet=category#facet-category">category</a>, <a href="/results/articles?_facet=illustrated#facet-illustrated">illustrated</a>, <a href="/results/articles?_facet=corrections#facet-corrections">corrections</a>, <a href="/results/articles?_facet_date=date#facet-date">date</a> (date)
    </p>
    <table class="rows-and-columns">
        <thead>
            <tr>
                    <th class="col-Link" scope="col">
                            Link
                    </th>
                    <th class="col-rowid" scope="col">
                                <a href="/results/articles?_sort_desc=rowid" rel="nofollow">rowid&nbsp;▼</a>
                    </th>
```

**Comment by simonw** [comment]
I have a hunch about this: maybe thte URLs that work are the ones that use `{{ base_url }}` directly in the template, while the ones that break are the ones that reconstruct the URL based on the incoming path?

**Comment by simonw** [comment]
Here's the output of the `/-/asgi-scope` plugin:
```
{'client': ('10.12.3.15', 0),
 'headers': [(b'cookie',
              b''),
             (b'upgrade-insecure-requests', b'1'),
             (b'dnt', b'1'),
             (b'accept-encoding', b'gzip'),
             (b'accept-language', b'en-US,en;q=0.5'),
             (b'accept',
              b'text/html,application/xhtml+xml,application/xml;q=0.9,image/'
              b'webp,*/*;q=0.8'),
             (b'user-agent',
              b'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko'
              b'/20100101 Firefox/74.0'),
             (b'x-scheme', b'https'),
             (b'x-original-uri',
              b'/user/wragge-datasette-test-czqms2oy/proxy/8001/-/asgi-scope'),
             (b'x-forwarded-proto', b'https,http'),
             (b'x-forwarded-port', b'443,80'),
             (b'x-forwarded-host', b'hub.gke.mybinder.org'),
             (b'x-forwarded-for', b'148.64.98.14,10.12.3.15'),
             (b'x-real-ip', b'148.64.98.14'),
             (b'connection', b'close'),
             (b'host', b'hub.gke.mybinder.org'),
             (b'x-forwarded-context',
              b'/user/wragge-datasette-test-czqms2oy/proxy/8001'),
             (b'x-proxycontextpath',
              b'/user/wragge-datasette-test-czqms2oy/proxy/8001')],
 'http_version': '1.1',
 'method': 'GET',
 'path': '/-/asgi-scope',
 'query_string': b'',
 'raw_path': b'/-/asgi-scope',
 'root_path': '',
 'scheme': 'https,http',
 'server': ('127.0.0.1', 8001),
 'type': 'http'}
```

**Comment by simonw** [comment]
Aha! It turns out my demo at https://github.com/simonw/jupyterserverproxy-datasette-demo suffers from the same bug.

**Comment by simonw** [comment]
I think the solution here may be to let the incoming `x-original-uri` header over-ride the `raw_path` used by Datasette. This may require a new Datasette setting.

**Comment by simonw** [comment]
I'm running this latest release like so:

Launch this binder: https://mybinder.org/v2/gh/wragge/datasette-test/master?urlpath=lab

Open the notebook.

In the notebook run this:

`!pip install https://github.com/simonw/datasette/archive/7b205af0b53c92d17b69f8c95d70a24a0c06ebce.zip`

Then this:

`!pip install datasette-debug-asgi`

And use this block to run Datasette:

```
# Get current running servers
servers = list_running_servers()

# Get the current base url
base_url = next(servers)['base_url']

# Create a base url for Datasette suing the proxy path
proxy_url = f'{base_url}proxy/8001/'

# Display a link to Datasette
display(HTML(f'<p><a href="{proxy_url}">View Datasette</a> (Click on the stop button to close the Datasette server)</p>'))

# Launch Datasette
!datasette -- results.db --port 8001 --config base_url:$proxy_url --config path_from_header:x-original-uri --config template_debug:1
```

**Comment by simonw** [comment]
Woohoo that worked!
<img width="1386" alt="results__articles__400_rows" src="https://user-images.githubusercontent.com/9599/77609678-db0b4c80-6edd-11ea-947b-1f7b1f14f56e.png">

**Comment by wragge** [comment]
Great! Yes, can confirm that this works on Binder. However, when I try to run the same code locally, I get an Internal Server Error when I try to access Datasette.

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Volumes/Workspace/mycode/datasette-test/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Volumes/Workspace/mycode/datasette-test/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Volumes/Workspace/mycode/datasette-test/lib/python3.7/site-packages/datasette_debug_asgi.py", line 24, in wrapped_app
    await app(scope, recieve, send)
  File "/Volumes/Workspace/mycode/datasette-test/lib/python3.7/site-packages/datasette/utils/asgi.py", line 174, in __call__
    await self.app(scope, receive, send)
  File "/Volumes/Workspace/mycode/datasette-test/lib/python3.7/site-packages/datasette/tracer.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/Volumes/Workspace/mycode/datasette-test/lib/python3.7/site-packages/datasette/app.py", line 746, in __call__
    raw_path = dict(scope["headers"])[path_from_header.encode("utf8")].split(b"?")[0]
KeyError: b'x-original-uri'
INFO:     127.0.0.1:49320 - "GET / HTTP/1.1" 500 Internal Server Error
```

**Comment by wragge** [comment]
Following on from @betatim's suggestion on Twitter, I've changed the proxy url to include 'absolute'.

``` python
proxy_url = f'{base_url}proxy/absolute/8001/'
```
This works both on Binder and locally, without using the `path_from_header` option. I've updated the demo repository. Sorry @simonw if I've led you down the wrong path!

**Comment by simonw** [comment]
Hooray! This is a really great fix, thanks.

**Comment by simonw** [comment]
And for https://github.com/simonw/jupyterserverproxy-datasette-demo setting `"absolute_url": True` appears to fix the bug as well (it previously caused an infinite redirect loop but that seems not to happen any more with the latest `base_url` setting): https://github.com/simonw/jupyterserverproxy-datasette-demo/commit/880f9d50566357160b793557f145c99e74ad759a
