### ISSUE TITLE
db.execute_write_fn(create_tables, block=True) hangs a thread if connection fails

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#935]
Discovered in https://github.com/simonw/latest-datasette-with-all-plugins/issues/3#issuecomment-674449757

**Comment by simonw** [comment]
The bug is here:

https://github.com/simonw/datasette/blob/13b3b51087964d5e1a8c1cdd2495e07bdbe176b8/datasette/database.py#L89-L100

If `conn = self.connect(write=True)` raises an exception the entire server hangs, like this:
```
% datasette -i fixtures.db  --get /            
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/simon/.local/share/virtualenvs/latest-datasette-with-all-plugins-PJL_Xy9e/lib/python3.8/site-packages/datasette/database.py", line 92, in _execute_writes
    conn = self.connect(write=True)
  File "/Users/simon/.local/share/virtualenvs/latest-datasette-with-all-plugins-PJL_Xy9e/lib/python3.8/site-packages/datasette/database.py", line 55, in connect
    assert not (write and not self.is_mutable)
AssertionError

... server hangs here ...
```

**Comment by simonw** [comment]
The easiest way to recreate this is to attempt a write against an immutable database, which triggers this assertion error:

https://github.com/simonw/datasette/blob/13b3b51087964d5e1a8c1cdd2495e07bdbe176b8/datasette/database.py#L47-L55

**Comment by simonw** [comment]
This implementation seems to fix it, need to work out how to test though.
```diff
diff --git a/datasette/database.py b/datasette/database.py
index ffa7a79..7ba1456 100644
--- a/datasette/database.py
+++ b/datasette/database.py
@@ -89,14 +89,22 @@ class Database:
     def _execute_writes(self):
         # Infinite looping thread that protects the single write connection
         # to this database
-        conn = self.connect(write=True)
+        conn_exception = None
+        conn = None
+        try:
+            conn = self.connect(write=True)
+        except Exception as e:
+            conn_exception = e
         while True:
             task = self._write_queue.get()
-            try:
-                result = task.fn(conn)
-            except Exception as e:
-                print(e)
-                result = e
+            if conn_exception is not None:
+                result = conn_exception
+            else:
+                try:
+                    result = task.fn(conn)
+                except Exception as e:
+                    print(e)
+                    result = e
             task.reply_queue.sync_q.put(result)
 
     async def execute_fn(self, fn):
```
